package exceptionGenerator;

/**
* exceptionGenerator/GeneratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exGen.idl
* 28 марта 2022 г. 0:01:05 MSK
*/

public final class GeneratorHolder implements org.omg.CORBA.portable.Streamable
{
  public exceptionGenerator.Generator value = null;

  public GeneratorHolder ()
  {
  }

  public GeneratorHolder (exceptionGenerator.Generator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exceptionGenerator.GeneratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exceptionGenerator.GeneratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exceptionGenerator.GeneratorHelper.type ();
  }

}
