package exceptionGenerator;


/**
* exceptionGenerator/Generator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exGen.idl
* 28 марта 2022 г. 0:01:05 MSK
*/

public interface Generator extends GeneratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Generator
