package exceptionGenerator;


/**
* exceptionGenerator/GeneratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exGen.idl
* 28 марта 2022 г. 0:01:05 MSK
*/

public interface GeneratorOperations 
{
  String Generate ();
  void Generate (String newGenerate);
} // interface GeneratorOperations
